<?php

namespace Larangogon\ThreeDS\Tests;

use GuzzleHttp\Exception\GuzzleException;
use Illuminate\Support\Facades\Mail;
use Larangogon\ThreeDS\Concrete\ThreeDSConcrete;
use Larangogon\ThreeDS\Mail\ErrorMail;
use Larangogon\ThreeDS\processThreeDS;
use Larangogon\ThreeDS\Traits\ProcessableTrait;
use PHPUnit\Framework\TestCase;

class ProcessTest extends TestCase
{
    use ProcessableTrait;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->data = [];
        $this->emailName = env('EMAIL');
        $this->token = env('TOKEN');
    }


    /**
     * @test
     */
    public function createRequest()
    {
        $threeDS = new ThreeDSConcrete();
        $threeDS->process($this->data, $this->emailName, $this->token);
    }

    /**
     * @test
     */
    public function processThreeDS()
    {
        $threeDS = new processThreeDS();
        $threeDS->createRequest($this->data, $this->emailName, $this->token);
    }


    /**
     * @test
     */
    public function processPaymentMailTest()
    {
        $error = ['The field is required.'];
        Mail::fake();

        $email = new ErrorMail($this->emailName, $error);
        Mail::to($this->emailName)->send($email);

        Mail::assertSent(ErrorMail::class);
    }

    /**
     * @test
     * @throws GuzzleException
     */
    public function status()
    {
        $response = $this->request($this->data, $this->emailName, $this->token);

        $response->assertStatus(200);
    }
}
