<?php

namespace Larangogon\ThreeDS\Tests;

use GuzzleHttp\Exception\GuzzleException;
use Illuminate\Support\Facades\Mail;
use Larangogon\ThreeDS\Mail\ErrorMail;
use Larangogon\ThreeDS\processThreeDS;
use Larangogon\ThreeDS\Traits\ProcessableTrait;
use PHPUnit\Framework\TestCase;

class ProcessTest extends TestCase
{
    use ProcessableTrait;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->emailName = env('EMAIL', 'johannitaarango2@gmail.com');
        $this->token = env('TOKEN', '234567dfghjfgh567');
    }

    /**
     * @test
     */
    public function processThreeDS()
    {
        $data = collect(
            [
                [
                    'id' => 1,
                    'name' => 'EGM Ingenieria sin frondteras',
                    'brand' => 'placetopay',
                    'country' => 'COL',
                    'currency' => 'COP',
                    'type' => 'RUT',
                    'number' => '123456789-0',
                    'url' => 'https://www.placetopay.com',
                    'mcc' => 742,
                    'isicClass' => 111,
                    'nameBranch' => 'Oficina principal',
                    'franchise' => 1,
                    'acquirerBIN' => 12345678910,
                    'version' => 2,
                    'invitations' => null
                ],
                [
                    'id' => 2,
                    'name' => 'EGM Ingenieria sin frondteras',
                    'brand' => 'placetopay',
                    'country' => 'COL',
                    'currency' => 'COP',
                    'type' => 'RUT',
                    'number' => '123456789-0',
                    'url' => 'https://www.placetopay.com',
                    'mcc' => 742,
                    'isicClass' => 111,
                    'nameBranch' => 'Oficina principal',
                    'franchise' => 1,
                    'acquirerBIN' => 12345678910,
                    'version' => 2,
                    'invitations' => null
                ]
            ]
        );
        $threeDS = new processThreeDS();
        $threeDS->createRequest($data, $this->emailName, $this->token);
    }

    /**
     * @test
     * @throws GuzzleException
     */
    public function status()
    {
        $data = collect(
            [
                [
                    'id' => 1,
                    'name' => 'EGM Ingenieria sin frondteras',
                    'brand' => 'placetopay',
                    'country' => 'COL',
                    'currency' => 'COP',
                    'type' => 'RUT',
                    'number' => '123456789-0',
                    'url' => 'https://www.placetopay.com',
                    'mcc' => 742,
                    'isicClass' => 111,
                    'nameBranch' => 'Oficina principal',
                    'franchise' => 1,
                    'acquirerBIN' => 12345678910,
                    'version' => 2,
                    'invitations' => null
                ],
                [
                    'id' => 2,
                    'name' => 'EGM Ingenieria sin frondteras',
                    'brand' => 'placetopay',
                    'country' => 'COL',
                    'currency' => 'COP',
                    'type' => 'RUT',
                    'number' => '123456789-0',
                    'url' => 'https://www.placetopay.com',
                    'mcc' => 742,
                    'isicClass' => 111,
                    'nameBranch' => 'Oficina principal',
                    'franchise' => 1,
                    'acquirerBIN' => 12345678910,
                    'version' => 2,
                    'invitations' => null
                ]
            ]
        );

        $this->request($data, $this->emailName, $this->token);
    }

    /**
     * @test
     */
    public function processPaymentMailTest()
    {
        $error = ['The field is required.'];
        Mail::fake();

        $email = new ErrorMail($this->emailName, $error);
        Mail::to($this->emailName)->send($email);

        Mail::assertSent(ErrorMail::class);
    }
}
